matrix:
  include:
    - name: "Android ARM"
      env: ARCH="arm"
    - name: "Android ARM 64"
      env: ARCH="arm64"
    - name: "Android x86"
      env: ARCH="x86"
    - name: "Android x86-64"
      env: ARCH="x86_64"
script:
  - chmod +x *.sh
  - mkdir out
  - export DEPLOY_DIR=$(pwd)/out
  - source ./get-ndk.sh
  - ./build-jerryscript.sh
  - ./build-lua.sh
  - ./build-lua-jit.sh
  - ./deploy.sh
