matrix:
  include:
    - name: "Android ARM"
      env: ARCH="arm"
    - name: "Android ARM 64"
      env: ARCH="arm64"
    - name: "Android x86"
      env: ARCH="x86"
    - name: "Android x86-64"
      env: ARCH="x86_64"
addons:
  apt:
    sources:
      - deadsnakes
    packages:
      - autoconf2.13
      - python3.6
install:
  - curl https://sh.rustup.rs -sSf | sh -s -- -y
script:
  - source ~/.cargo/env
  - export API_LEVEL=21
  - chmod +x *.sh
  - mkdir out
  - export DEPLOY_DIR=$(pwd)/out
  - source ./get-ndk.sh
  - ./build-jerryscript.sh
  - ./build-lua.sh
  - ./build-spidermonkey.sh
  - ./deploy.sh
